FROM golang:1.20 AS build
WORKDIR /go/src

COPY go.mod go.sum ./
COPY staff/server staff/server

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -a -installsuffix cgo -o replaystaff staff/server/main.go

FROM scratch AS runtime
COPY --from=build /go/src/replaystaff ./
EXPOSE 8080/tcp
ENTRYPOINT ["./replaystaff"]
