FROM golang:1.20 AS build
WORKDIR /go/src

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY ingest/server ingest/server
COPY store store

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -a -installsuffix cgo -o replayinfo ingest/server/main.go

FROM scratch AS runtime
COPY --from=build /go/src/replayinfo ./
EXPOSE 8080/tcp
ENTRYPOINT ["./replayinfo"]
