/*
 * GoBun File Info
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Graphql struct {

	Data map[string]interface{} `json:"data,omitempty"`

	Errors []map[string]interface{} `json:"errors,omitempty"`
}

// AssertGraphqlRequired checks if the required fields are not zero-ed
func AssertGraphqlRequired(obj Graphql) error {
	return nil
}

// AssertRecurseGraphqlRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Graphql (e.g. [][]Graphql), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGraphqlRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGraphql, ok := obj.(Graphql)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGraphqlRequired(aGraphql)
	})
}
