/*
 * GoBun File Info
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Replay struct {

	Title string `json:"Title,omitempty"`

	GameMap float32 `json:"GameMap,omitempty"`

	Time float32 `json:"Time,omitempty"`

	Lap float32 `json:"Lap,omitempty"`

	PlayerEntries []PlayerEntry `json:"PlayerEntries,omitempty"`
}

// AssertReplayRequired checks if the required fields are not zero-ed
func AssertReplayRequired(obj Replay) error {
	for _, el := range obj.PlayerEntries {
		if err := AssertPlayerEntryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseReplayRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Replay (e.g. [][]Replay), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseReplayRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aReplay, ok := obj.(Replay)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertReplayRequired(aReplay)
	})
}
